route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#test'
            api_url: 'https://hooks.slack.com/services/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'
