global:
  scrape_interval: 1m
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prom1'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'localhost:9093'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# remote_read:
#  - url: http://localhost:9090/api/v1/read

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - filesd.json


